#!/bin/bash
set -x

branchName=$1
repository=$2
platform=$3
currentVersion=$4
newVersion=$5

export JAVA_HOME=$6
export JAVA=$7

echo "BEFORE if ${JAVA_HOME}"
if [[ "$branchName" =~ renovate/quarkus ]]; then
  echo "INSIDE if ${JAVA_HOME}"
  echo "INSIDE if ${JAVA}"
  echo "HELLO FROM SCRIPT"
  /tmp/renovate/repos/$platform/$repository/mvnw versions:set-property -Dproperty=quarkus-maven-plugin -DnewVersion=$currentVersion -f /tmp/renovate/repos/$platform/$repository/pom.xml
  /tmp/renovate/repos/$platform/$repository/mvnw -f /tmp/renovate/repos/$platform/$repository/pom.xml io.quarkus.platform:quarkus-maven-plugin:$newVersion:update
fi