name: Trigger Renovate

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Verify Java
        run: java -version

      - name: Self-hosted Renovate
        run: |
          docker run --rm \
            -e RENOVATE_TOKEN=${{ secrets.RENOVATE_TOKEN }} \
            -e LOG_LEVEL=debug \
            -v ${{ github.workspace }}:/mnt/renovate \
            -v /var/run/docker.sock:/var/run/docker.sock \
            ghcr.io/Ruhsi/gepardec-renovate:latest \
            renovate
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          LOG_LEVEL: debug
#      - name: Self-hosted Renovate
#        uses: renovatebot/github-action@v40.1.12
#        with:
#          token: ${{ secrets.RENOVATE_TOKEN }}
#          configurationFile: renovate-config.js
#        env:
#          LOG_LEVEL: debug

      - name: Run ls -l
        run: ls -l